### ISSUE TITLE
Joan of Arc Prime and Jan Zizka

### ISSUE THREAD

**Issue by MrDolphinCodes** [sho-87/rok-talents#44]
Joan of Arc Prime and Jan Zizka were just added to Rise of Kingdoms a bit ago for SoC kingdoms. It would be greatly appreciated if you added the two commanders.

**Comment by sho-87** [comment]
do you know where I can get screenshots of the character portrait from? I seems rok.guide hasn't updated their commander list in a while

I need to be able to extract an image that looks similar to this with the frame:

https://raw.githubusercontent.com/sho-87/rok-talents/master/public/images/commanders/Bertrand%20du%20Guesclin.png

**Comment by MrDolphinCodes** [comment]
I’m not sure where you can access their trees. Joan of Arc Prime is Cavalry, Versatility, and Support and Jan is Cavalry, Garrison, Skill. I have a discord bot which gives the best talent trees for each commander when given a command. This is the image of the talent tree I am using for Joan of Arc 
![E4D22988-C098-461D-AFE6-7A20910DA302](https://user-images.githubusercontent.com/106354581/192919525-a2cceafd-d5b6-4b22-a99b-124cac6fe7a5.png)
I haven’t made one for Jan since you can’t obtain him yet (no testing is possible because of this) but I’ll send an image of it once I get it done

**Comment by MrDolphinCodes** [comment]
This is the Joan of Arc commander icon:
<img width="935" alt="Screen Shot 2022-09-28 at 8 55 50 PM" src="https://user-images.githubusercontent.com/106354581/192920913-91bb1f0f-97a3-46c9-b41f-961412729f7d.png">

**Comment by MrDolphinCodes** [comment]
Thanks for all your hard work!
