### ISSUE TITLE
Cheok Jun Gyeong Talent Build

### ISSUE THREAD

**Issue by MrDolphinCodes** [sho-87/rok-talents#45]
Cheok Jun Gyeong is an Infantry, Versatility, Attack commander but it shows Infantry, Versatility, Skill instead
<img width="1440" alt="Screen Shot 2022-10-04 at 8 36 24 AM" src="https://user-images.githubusercontent.com/106354581/193833784-3f983ba5-7852-409c-81c0-89c149da705e.png">
<img width="821" alt="Screen Shot 2022-10-04 at 8 37 24 AM" src="https://user-images.githubusercontent.com/106354581/193834010-20a7d5f9-3894-4c22-8007-b0f13c5226d6.png">

**Comment by sho-87** [comment]
Fixed! site should update as soon as the cache refreshes
