### ISSUE TITLE
Add Queen Tamar of Georgia

### ISSUE THREAD

**Issue by MrDolphinCodes** [sho-87/rok-talents#46]
I was looking through the list of commanders and realized that Queen Tamar of Georgia was missing in the list of epic commanders. This is her talent build:
![blank-canvas-designs_99](https://user-images.githubusercontent.com/106354581/194372986-07d5f67b-2d41-4a20-a5f4-a2babd980158.png)

**Comment by sho-87** [comment]
do you have a higher res image of her icon, either from ingame or from the talent builder bot? I dont have the game installed anymore

**Comment by MrDolphinCodes** [comment]
Here is a higher res image of her icon:
<img width="78" alt="Screen Shot 2022-10-07 at 8 49 00 AM" src="https://user-images.githubusercontent.com/106354581/194569088-04ad75f7-5f6e-4069-bbc5-7352d540ef3f.png">

**Comment by sho-87** [comment]
thanks! done: https://github.com/sho-87/rok-talents/commit/22273625677a11e54de08927dc01a39dea150b71
