### ISSUE TITLE
New infantry commanders Tariq and Sargon

### ISSUE THREAD

**Issue by Crabapples86** [sho-87/rok-talents#47]
Please add their icons if you can, thanks!

**Comment by sho-87** [comment]
do you have any high res images of their ingame icons from the talent screen? like this: https://github.com/sho-87/rok-talents/issues/46

**Comment by Crabapples86** [comment]
Hi, will these do? Thanks!

**Comment by sho-87** [comment]
@Crabapples86 dont think the images attached due to using email reply

I can add the commanders in using temporary blank images for now, and then update later when actual images come in

**Comment by Crabapples86** [comment]
![Screenshot_20230104-181320_5120d670f9a8ec405bc0abf0056c8329](https://user-images.githubusercontent.com/108036134/210607397-ad86dcda-6f0d-4e26-aaef-2bdfbb1dff93.jpg)
![Screenshot_20230104-181123_5120d670f9a8ec405bc0abf0056c8329](https://user-images.githubusercontent.com/108036134/210607419-ee2016a5-e2c4-4850-9ede-8d084555ea7e.jpg)
How about now?

**Comment by sho-87** [comment]
perfect! will add them later today
